### ISSUE TITLE
Increment the activities json

### ISSUE THREAD

**Issue by vitorboccio** [drewthoennes/Bored-API#13]
Hello,

Is the activities json still being updated regularly ? I've submitted few suggestions to increment it but seems to not be there.
I am keen to help and review all the received suggestions if necessary.
Just give me instructions how to proceed.

**Comment by Perlkonig** [comment]
I was just going to say the same thing! It says 9 months ago, but I also just submitted a bunch. Let me know if I can help in any way.

**Comment by drewthoennes** [comment]
Hi all, and thanks for your interest in the project! The activities have not been updated regularly, but I am going through and updating them right now. I should have a commit up tonight with the changes.

I often get busy with my classes and my student organizations, so I can't always make time to delve into the database, filter out the spam, and aggregate the new activities. Feel free to submit a pull request here if you have a really interesting idea for an activity, as it is easier for me to add them via pull requests than it is the suggestion system.

**Comment by Perlkonig** [comment]
Glad to hear it's active. I totally understand life getting in the way :) I started by forking and prepping for a PR, but there are fields like OID that I'm not sure how you want to populate. If you expand the contributing guidelines, I will gladly go that route.

But I didn't write down the dozen or so contributions I just made! So I can't remember them all now. Hopefully they'll get through eventually.

Thanks! This is such a great idea!

**Comment by vitorboccio** [comment]
Yea, the same for me. Not sure how to generate the OIDs. Let us know if you need further support maintaining the project. It's very useful 👍

**Comment by drewthoennes** [comment]
I just added suggested activities to the database in [this commit](https://github.com/drewthoennes/Bored-API/commit/a0582ec60f56ea94ce8634ff937c52a9347c9ce2). I also simplified the activities.json file to make it easier to make pull requests.

Thanks again for the support and happy coding!

**Comment by Perlkonig** [comment]
Thanks! What value do you want for the key? Just any unique integer? Just want to make sure I do the PR correctly.

**Comment by drewthoennes** [comment]
Yes, I use [this function](https://github.com/drewthoennes/Bored-API/blob/master/src/backend/utils/methods.js#L6) to generate a random number between 1000000 and 9999999 to use as a unique key.
