### ISSUE TITLE
Accessibility and Price Questions

### ISSUE THREAD

**Issue by Perlkonig** [drewthoennes/Bored-API#16]
It would be helpful if your continuums were bounded on both ends.

If accessibility 0 is "most accessible", is 1 "impossible"? This is really challenging to mentally parse. What is a 0.5 as opposed to a 0.6, for example? What precisely do you mean by "accessible"? Often this refers to people with disabilities. Is that the intent here?

If price 0 is "free", what is 1? "Prohibitively expensive"? Again, what's the difference between 0.5 and 0.6?

## Price
- One approach is a subjective scale like 0 (free), 1 (trivial cost), 2 (minor cost), 3 (major cost)
- Another is to turn it into an actual estimate of dollar price. Again, 0 is free, but maybe "Go to a movie with friends" might become `30` or whatever it might reasonably cost for one person to go to the movie and get popcorn.
- Or, if you want to keep the 0-1 range, you could say that 1 = >$100 or >$1000 and then you scale the cost based on that.

## Accessibility
- If this is meant to refer to disability or age, then a finite integer scale is probably simplest: 0 (easy for almost everyone), 1 (may pose minor challenges to someone with a disability or elderly), 2 (definitely pose some challenge to someone with a disability or elderly), 3 (very difficult for someone with a disability or elderly)

Still subjective, but if documented, would be more useful than the 0-1 scale.

Anyway, just some ideas.

**Comment by drewthoennes** [comment]
Hi @Perlkonig all great questions!

When I first built the API, I added these two fields as decimals between 0 - 1 without fully thinking through the implications and scalability of it. The system I have right now was simple to implement, but has certainly been hard to maintain and explain.

By accessibility, I meant how possible it would be to do some activity, though looking at it now I definitely intermingled which end signifies accessible. This would be something we could only hope to correct as to not change the API.

Changing these to integers would be much better and is something I've been considering for some time, but that would have to be in v2 of the API since the current one sees tens of thousands of endpoint hits per day. For now, correcting my past errors is probably the smartest plan of action.

**Comment by Perlkonig** [comment]
I get not wanting to change the API. One possible approach is to simply add some semantics—some signposts along the continuum to give it some grounding. If we can land on something you're comfortable with, I can update the `activities.json` file and the docs.

## Price
It seems to me your goal is to collect together mostly easy and inexpensive things one can do, so I recommend that 0 continue to represent "free" and that 1 represent "$100 or more." The tenths place then represents increments of 10 dollars. (So a value of 0.2 would be "approximately $20.") It's still somewhat subjective, but it's more concrete.

Another alternative is to be less granular and simply assign meaning (in the documentation) to five (or however many you want) points along the line:
* 0 = Free
* 0.25 = Trivial cost
* 0.5 = Moderate cost
* 0.75 = Expensive
* 1 = Very expensive

## Accessibility
Same goes here. Since there's no concrete representation of accessibility, I think you just pick some signposts along the way and define them in the docs. I agree that 1 seems the most logical signifier of "most accessible." But you still have the issue of defining "accessible." You can do it any way you want, but you want to make that definition explicit for the number to be useful.

If "accessible" to you refers to disability, then you could use the scale in my previous message and assign them to 0, 0.3, 0.6, and 1, respectively.

Or if you just mean "available", then maybe something like the following:
* 0 = Very challenging to do or requires very specialized resources
* 0.5 = Some challenges finding the necessary resources
* 1 = No or only trivial challenge finding the necessary resources

**Comment by drewthoennes** [comment]
Thanks for all of these great suggestions! They directly impacted how I implemented v2 of the API, and I think it's much more understandable and concise now.

Feel free to checkout the [api-v2](https://github.com/drewthoennes/Bored-API/tree/api-v2) branch to see how it works. This is running in production, it just isn't documented yet.
