### ISSUE TITLE
v2 suggestions

### ISSUE THREAD

**Issue by Perlkonig** [drewthoennes/Bored-API#19]
If you ever do want to update the API, then here are some new fields to consider to make the search more granular.

* `duration`: A measure of how long an activity takes. Could be text or integer, but it should be discrete: `minutes`, `hours`, `days`, `weeks`.

* `accessibility`: Redefined to focus on disability/health/age. At the very least, `no challenges`, `minor challenges`, `major challenges`.

* `resources` or `availability` etc.: The former "accessibility" field but now focused on the resources needed to accomplish the task: `no specialized resources needed`, `some easy-to-find resources needed`, `some specialized resources needed`, `very specialized equipment required`.

* `kidfriendly`: A simple boolean flag would do.

It would also be nice to allow for multiple "types" and to revisit the type taxonomy, maybe adding some hierarchy.

**Comment by Perlkonig** [comment]
I've been accused before of being overly interested in taxonomy, so maybe this is too much, but I think it would be interesting to create a hierarchy that makes search more useful. The `type` would consist of three levels and then a set of `tags`.

* Top-level type would indicate the overall focus: `self` and/or `other`
* Mid-level would broadly categorize things into `recreation` (stuff for fun), `busywork` (life chores), and `charity` or `altruism` (stuff you do for the greater good).
* Bottom level would classify the fundamental verb of the activity: `learn`, `create`, `do`.
* Finally, each activity could have multiple `tags` that would be the granular classifications like `food`, `music`,`books`,`movies`,`tv`,`sports`,etc.

You could implement such a system using byte codes (like `chmod` masks), which would effectively allow multiple fields to be selected. This particular system only has 8 total options.

Examples:
* "Surprise your significant other with something considerate" could be classified as `other | charity | do`
* "Learn Kotlin" could be `self | recreation | learn`
* "Bake a pie with some friends" could be `other | recreation | create`
* ""Shred old documents you don't need anymore" would be `self | busywork | do`

Can you tell I'm getting a little bored over here?! Thanks for giving me something to work on today!

**Comment by drewthoennes** [comment]
I also wrapped some of these suggestions into the v2 API, including `duration` and `kidFriendly`!

I was interested in all that you suggested on the taxonomy, but personally I think what we have now suits the needs of the application. If or when the list of activities grows to be overly large, we should definitely revisit the taxonomy to see if we can leverage your suggestions to make the API more usable! Thanks again for all of your hard work and dedication!!
