### ISSUE TITLE
How many items do you have in your database?

### ISSUE THREAD

**Issue by dosymbaev** [drewthoennes/Bored-API#2]

**Comment by drewthoennes** [comment]
Hey @dosymbaev , thanks for your interest in the project! There are currently 132 activities in the database and you can all of them [here](https://github.com/drewthoennes/Bored-API/blob/master/database.json)

**Comment by sandrina-p** [comment]
Hi @drewthoennes. I have the same question. The link you provided is broken. Is there any new link? Thank you!

Edit: Oh, gotcha. The [link updated](https://github.com/drewthoennes/Bored-API/blob/master/db/activities.json)

Also, extra question: Is there an endpoint to know how many different activity types exist?
