### ISSUE TITLE
Is it possible to filter search with multiple parameters?

### ISSUE THREAD

**Issue by amandalok10** [drewthoennes/Bored-API#21]
Can I filter with multiple parameters like: 
activity?type=recreational&participants=3

Also, is the maximum number of participants 5?

**Comment by drewthoennes** [comment]
Hi @amandalok10 ! It is possible to apply multiple filters, such as with [type and participants](https://www.boredapi.com/api/activity?type=social&participants=2). Using any of the min or max filters will override the normal filter though, so minparticipants overrides participants like in [this example](https://www.boredapi.com/api/activity?type=social&participants=2&minparticipants=3).

To answer your second question, technically there is no maximum number of participants, but the max right now is 8 seen [here](https://www.boredapi.com/api/activity?participants=8).

I hope this answers your questions!
