### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kokone** [drewthoennes/Bored-API#3]
Hello, I was wondering what the license for this database is? If I include it in my own project so it can work offline, is that allowed, what's the deal with attribution, etc. 

Please let me know, thanks!

**Comment by drewthoennes** [comment]
Hey @kokone , thanks for your interest in the project! I just added an MIT license, so you're free to reuse and redistribute any of the code. I'd appreciate it if you credited me in some capacity, but you don't have to.

**Comment by kokone** [comment]
Cheers @drewthoennes ! I'll absolutely credit you.
