### ISSUE TITLE
[Question] Are keys intentionally returned as strings?

### ISSUE THREAD

**Issue by dmitriy-shmilo** [drewthoennes/Bored-API#4]
Looking at this sample output when requesting `https://www.boredapi.com/api/activity`:

```json
{
"activity":"Go to a concert with some friends",
"accessibility":0.4,
"type":"social",
"participants":4,
"price":0.6,
"key":"4558850"
}
```

Most of the numeric data is being returned as numbers, like price and participants. But `key` field on an Activity is a string. Is this intentional? Is it safe to assume that this string contains only numbers and so can be stored in a big unsigned integer?

Thank you.

**Comment by drewthoennes** [comment]
Thanks for your interest in the project! I originally did this because the keys were going to be alphanumeric, but after the fact I decided to just use numeric keys. As far as I know, the key works correctly right now, but if you see a reason to change it, feel free to submit a pull request.

**Comment by dmitriy-shmilo** [comment]
Understood, thank you.
