### ISSUE TITLE
MongoError

### ISSUE THREAD

**Issue by MaryRemo** [drewthoennes/Bored-API#5]
API stopped working
Throwing a MongoError

**Comment by drewthoennes** [comment]
I restarted the application and the API is now working. I don't know if this was an issue with Heroku or my code, but I'll be looking into it to prevent this from happening in the future. Thanks again for catching this!

**Comment by MaryRemo** [comment]
Awesome! No problem! Thanks you!

**Comment by Phoenix404** [comment]
The Error come back. Can you fix it again, please?

**Comment by drewthoennes** [comment]
@Phoenix404 Thanks for letting me know that it wasn't working! I just restarted it and it's back up now. This is an error with Heroku and mLab and thankfully not my code. I'll work on writing a script to check for these errors and restart when needed.

**Comment by Phoenix404** [comment]
That would be great. Thanks man
