### ISSUE TITLE
Participants more than 1

### ISSUE THREAD

**Issue by ChrisvdLeij** [drewthoennes/Bored-API#6]
Cool API! Not really and issue i think but is it possible to set the participants on more than 1?

Somehting like: `?participants>1`

**Comment by drewthoennes** [comment]
Hey @ChrisvdLeij , thanks for checking out the project! I really liked your idea, so I added it into the API. Now if you want to find activities for multiple participants, you can use: `https://www.boredapi.com/api/activity?minparticipants=2`.
