### ISSUE TITLE
For the week starting Monday May 20th it seems the API is down.

### ISSUE THREAD

**Issue by tsmith4014** [drewthoennes/Bored-API#81]
Have not been able to get a good response this week.  Sites looks to be down.

**Comment by ssaunier** [comment]
Down for me as well. End of month => Heroku free dynos ran out of credits maybe?

Thanks for the service 🙌 !!

**Comment by cyteon** [comment]
Still down for me

**Comment by tsmith4014** [comment]
Still down here but yes thank you for the Free API, very much appreciated.

**Comment by cyteon** [comment]
New domain, just found in docs: https://bored-api.appbrewery.com/random

**Comment by PrincePazol** [comment]
This domain seems to work: https://bored.api.lewagon.com/

**Comment by ssaunier** [comment]
@PrincePazol this is for internal use as temporary backup for out Students & Teaching staff though, it can be pulled at anytime as soon as the original domain comes back alive. Thanks for your understanding 🙏
