### ISSUE TITLE
What data type should I use for `participants` field?

### ISSUE THREAD

**Issue by CommanderTvis** [drewthoennes/Bored-API#9]
What data type should I use for `participants` field? In the documentation its interval is [1, n]. What is the max possible n?

**Comment by drewthoennes** [comment]
Hi @CommanderTvis , thanks for checking out the project!

The data type for the participants is positive integers. That integer can vary (hence the [1, n]), but the max right now is 8.

For your reference, you can find all of the activities [here](https://github.com/drewthoennes/Bored-API/blob/master/activities.json). Happy New Year!
